"use strict";(self.webpackChunkhst_react_ui=self.webpackChunkhst_react_ui||[]).push([[401],{25697:function(l,e,t){var a;t.r(e),t.d(e,{demos:function(){return m}});var o=t(17061),u=t.n(o),i=t(17156),c=t.n(i),r=t(67294),d=t(6578),m={"primarybutton-demo-base":{component:r.memo(r.lazy(function(){return t.e(844).then(t.bind(t,14014))})),asset:{type:"BLOCK",id:"primarybutton-demo-base",refAtomIds:["PrimaryButton"],dependencies:{"index.tsx":{type:"FILE",value:t(84245).Z},"hst-react-ui":{type:"NPM",value:"0.0.1"},react:{type:"NPM",value:"18.3.1"}},entry:"index.tsx",title:"\u57FA\u7840\u7528\u6CD5"},context:{"hst-react-ui":d,react:a||(a=t.t(r,2))},renderOpts:{compile:function(){var v=c()(u()().mark(function I(){var s,P=arguments;return u()().wrap(function(n){for(;;)switch(n.prev=n.next){case 0:return n.next=2,t.e(250).then(t.bind(t,90250));case 2:return n.abrupt("return",(s=n.sent).default.apply(s,P));case 3:case"end":return n.stop()}},I)}));function h(){return v.apply(this,arguments)}return h}()}}}},6578:function(l,e,t){t.r(e),t.d(e,{PrimaryButton:function(){return s}});var a=t(42122),o=t.n(a),u=t(70215),i=t.n(u),c=t(27424),r=t.n(c),d=t(67294),m=t(81174),v=t(85893),h=["children"],I=function(f){var n=(0,d.useState)(!1),y=r()(n,2),E=y[0],p=y[1],x=f.children,B=i()(f,h),M=function(){p(!0),setTimeout(function(){p(!1)},1e3)};return(0,v.jsx)(m.ZP,o()(o()({},B),{},{type:"primary",onClick:M,loading:E,children:x}))},s=(0,d.memo)(I)},55288:function(l,e,t){t.r(e),t.d(e,{texts:function(){return a}});const a=[{value:"\u57FA\u7840\u7684\u6309\u94AE\u7EC4\u4EF6 HstButton\u3002",paraId:0,tocIndex:1},{value:"\u5C5E\u6027",paraId:1,tocIndex:4},{value:"\u7C7B\u578B",paraId:1,tocIndex:4},{value:"\u9ED8\u8BA4\u503C",paraId:1,tocIndex:4},{value:"\u5FC5\u586B",paraId:1,tocIndex:4},{value:"\u8BF4\u660E",paraId:1,tocIndex:4},{value:"size",paraId:1,tocIndex:4},{value:"small",paraId:1,tocIndex:4},{value:"  ",paraId:1,tocIndex:4},{value:"middle",paraId:1,tocIndex:4},{value:"  ",paraId:1,tocIndex:4},{value:"large",paraId:1,tocIndex:4},{value:"middle",paraId:1,tocIndex:4},{value:"false",paraId:1,tocIndex:4},{value:"\u6309\u94AE\u5927\u5C0F",paraId:1,tocIndex:4}]},84245:function(l,e){e.Z=`import { PrimaryButton } from 'hst-react-ui';
import React from 'react';


export default () => {

  return (
    <PrimaryButton>\u57FA\u7840\u6309\u94AE</PrimaryButton>
  );
}
`}}]);
